import { defineConfig } from 'oxfmt';

export default defineConfig({
  arrowParens: 'always',
  bracketSameLine: false,
  bracketSpacing: true,
  embeddedLanguageFormatting: 'auto',
  endOfLine: 'lf',
  htmlWhitespaceSensitivity: 'strict',
  insertPragma: false,
  jsxSingleQuote: false,
  printWidth: 80,
  proseWrap: 'preserve',
  quoteProps: 'as-needed',
  rangeStart: 0,
  rangeEnd: null,
  requirePragma: false,
  semi: true,
  singleAttributePerLine: true,
  singleQuote: true,
  trailingComma: 'all',
  tabWidth: 2,
  useTabs: false,
  sortPackageJson: false,
  ignorePatterns: [
    '.github',
    '.gitignore',
    '.gitattributes',
    '.nvmrc',
    'log/',
    'tmp/',
  ],
  sortImports: {
    groups: [
      'builtin',
      'external',
      'internal',
      'value-parent',
      ['value-index', 'value-sibling'],
      'style',
      'type',
    ],
  },
});
