module.exports = {
  complexity: 5,
  maxClassesPerFile: 1,
  arrayBracketNewlineMinItems: 4,
  arrayElementNewlineMinItems: 5,
  idLengthMax: 50,
  indent: 2,
  maxDepth: 2,
  maxLen: 150,
  maxLinesMax: 250,
  maxLinesPerFunctionMax: 100,
  maxNestedCallbacks: 3,
  maxParams: 4,
  maxStatements: 10,
  maxStatementsPerLine: 1,
  noMultipleEmptyLinesMax: 2,
  noMultipleEmptyLinesEOF: 0,
  noMultipleEmptyLinesBOF: 0,
  newlineObjectExpressionMin: 2,
  newlineObjectPatternMin: 4,
  newlineImportDeclarationMin: 4,
  newlineExportDeclarationMin: 4,
  importMaxDependenciesMax: 15,
};
