module.exports = {
  extends: ['./index.js'],

  rules: {
    '@stylistic/js/array-bracket-newline': 'off',
    '@stylistic/js/array-bracket-spacing': 'off',
    '@stylistic/js/array-element-newline': 'off',
    '@stylistic/js/arrow-parens': 'off',
    '@stylistic/js/arrow-spacing': 'off',
    '@stylistic/js/block-spacing': 'off',
    '@stylistic/js/brace-style': 'off',
    '@stylistic/js/comma-dangle': 'off',
    '@stylistic/js/comma-spacing': 'off',
    '@stylistic/js/comma-style': 'off',
    '@stylistic/js/computed-property-spacing': 'off',
    '@stylistic/js/dot-location': 'off',
    '@stylistic/js/eol-last': 'off',
    '@stylistic/js/func-call-spacing': 'off',
    '@stylistic/js/function-call-argument-newline': 'off',
    '@stylistic/js/function-paren-newline': 'off',
    '@stylistic/js/generator-star-spacing': 'off',
    '@stylistic/js/implicit-arrow-linebreak': 'off',
    '@stylistic/js/indent': 'off',
    '@stylistic/js/jsx-quotes': 'off',
    '@stylistic/js/key-spacing': 'off',
    '@stylistic/js/keyword-spacing': 'off',
    '@stylistic/js/linebreak-style': 'off',
    '@stylistic/js/multiline-ternary': 'off',
    '@stylistic/js/newline-per-chained-call': 'off',
    '@stylistic/js/new-parens': 'off',
    '@stylistic/js/no-extra-parens': 'off',
    '@stylistic/js/no-extra-semi': 'off',
    '@stylistic/js/no-floating-decimal': 'off',
    '@stylistic/js/no-mixed-spaces-and-tabs': 'off',
    '@stylistic/js/no-multi-spaces': 'off',
    '@stylistic/js/no-multiple-empty-lines': 'off',
    '@stylistic/js/no-trailing-spaces': 'off',
    '@stylistic/js/no-whitespace-before-property': 'off',
    '@stylistic/js/nonblock-statement-body-position': 'off',
    '@stylistic/js/object-curly-newline': 'off',
    '@stylistic/js/object-curly-spacing': 'off',
    '@stylistic/js/object-property-newline': 'off',
    '@stylistic/js/one-var-declaration-per-line': 'off',
    '@stylistic/js/operator-linebreak': 'off',
    '@stylistic/js/padded-blocks': 'off',
    '@stylistic/js/quote-props': 'off',
    '@stylistic/js/rest-spread-spacing': 'off',
    '@stylistic/js/semi': 'off',
    '@stylistic/js/semi-spacing': 'off',
    '@stylistic/js/semi-style': 'off',
    '@stylistic/js/space-before-blocks': 'off',
    '@stylistic/js/space-before-function-paren': 'off',
    '@stylistic/js/space-in-parens': 'off',
    '@stylistic/js/space-infix-ops': 'off',
    '@stylistic/js/space-unary-ops': 'off',
    '@stylistic/js/switch-colon-spacing': 'off',
    '@stylistic/js/template-curly-spacing': 'off',
    '@stylistic/js/template-tag-spacing': 'off',
    'unicode-bom': 'off',
    '@stylistic/js/wrap-iife': 'off',
    '@stylistic/js/wrap-regex': 'off',
    '@stylistic/js/yield-star-spacing': 'off',

    // Might be enabled
    '@stylistic/js/lines-around-comment': 'off',
    '@stylistic/js/no-mixed-operators': 'off',

    // Unicorn
    'unicorn/empty-brace-spaces': 'off',
    'unicorn/no-nested-ternary': 'off',
    'unicorn/number-literal-case': 'off',
  },
};
