name: PR
on: [pull_request]
jobs:
  pr:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install --ignore-scripts

      - name: ESLint
        run: npm run lint
