name: PR
on: [pull_request]
jobs:
  pr:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: avides/actions-project-version-check@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: package.json

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: ESLint
        run: npm run lint
